# Dockerfile

# Base Image: Python 3.13-slim dengan Debian Bullseye
FROM python:3.13-slim-bullseye

# Instal System Dependencies yang diperlukan
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        git \
        libopenblas-dev \
        liblapack-dev \
        libatlas-base-dev \
        gfortran \
        ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip, setuptools, wheel
RUN pip install --upgrade pip setuptools wheel

# Direktori Kerja
WORKDIR /app

# Instal Python Dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Salin Kode Aplikasi
COPY . .

# Expose port
EXPOSE 8000

# Run command
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]